In [33]:
from net_utils import MFA 
import torch.nn as nn
import torch

In [50]:
a = nn.Embedding(1, 3)
b = nn.LayerNorm(3)
a.weight

Parameter containing:
tensor([[-0.5143, -0.1271, -0.4543]], requires_grad=True)

In [23]:
b(a.weight)

tensor([[-1.0936, -0.2297,  1.3233]], grad_fn=<NativeLayerNormBackward0>)

In [55]:
a = torch.Tensor([[-0.5143, -0.1271, -0.4543]], requires_grad=True)

a.mean()

TypeError: new() received an invalid combination of arguments - got (list, requires_grad=bool), but expected one of:
 * (*, torch.device device)
      didn't match because some of the keywords were incorrect: requires_grad
 * (torch.Storage storage)
 * (Tensor other)
 * (tuple of ints size, *, torch.device device)
 * (object data, *, torch.device device)


In [32]:
a.weight.var()

tensor(5.7860, grad_fn=<VarBackward0>)

In [34]:
(a.weight - a.weight.mean())/ torch.sqrt(a.weight.var())

tensor([[-0.8929, -0.1876,  1.0805]], grad_fn=<DivBackward0>)